
# -------------------------------------------------------------------------
# 🚀 Created and distributed by The AltStack
# 🌍 https://thealtstack.com
# -------------------------------------------------------------------------


services:
  chaskiq:
    image: chaskiq/chaskiq:latest
    container_name: chaskiq
    restart: unless-stopped
    ports:
      - "3000:3000"

