# -------------------------------------------------------------------------
# 🚀 Created and distributed by The AltStack
# 🌍 https://thealtstack.com
# -------------------------------------------------------------------------

services:
  gimp:
    image: linuxserver/gimp:latest
    container_name: gimp
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - PUID=1000
      - PGID=1000
