
# -------------------------------------------------------------------------
# 🚀 Created and distributed by The AltStack
# 🌍 https://thealtstack.com
# -------------------------------------------------------------------------


services:
  krita:
    image: linuxserver/krita:latest
    container_name: krita
    restart: unless-stopped
    ports:
      - "3000:3000"

