
# -------------------------------------------------------------------------
# 🚀 Created and distributed by The AltStack
# 🌍 https://thealtstack.com
# -------------------------------------------------------------------------


services:
  librecad:
    image: lscr.io/linuxserver/librecad:latest
    container_name: librecad
    restart: unless-stopped
    ports:
      - "3000:3000"

