
# -------------------------------------------------------------------------
# 🚀 Created and distributed by The AltStack
# 🌍 https://thealtstack.com
# -------------------------------------------------------------------------


services:
  ollama-deepseek:
    image: ollama/ollama:latest
    container_name: ollama-deepseek
    restart: unless-stopped
    ports:
      - "11435:11434"
    volumes:
      - ollama_deepseek:/root/.ollama

volumes:
  ollama_deepseek:
