
# -------------------------------------------------------------------------
# 🚀 Created and distributed by The AltStack
# 🌍 https://thealtstack.com
# -------------------------------------------------------------------------


services:
  keepassxc:
    image: jlesage/keepassxc:latest
    container_name: keepassxc
    restart: unless-stopped
    ports:
      - "5800:5800"

