
# -------------------------------------------------------------------------
# 🚀 Created and distributed by The AltStack
# 🌍 https://thealtstack.com
# -------------------------------------------------------------------------


services:
  jitsu:
    image: jitsu/jitsu:latest
    container_name: jitsu
    restart: unless-stopped
    ports:
      - "8000:8000"

