#!/bin/bash
# 🚀 Auto-generated by The AltStack
# https://thealtstack.com

echo "🔵 Starting AltStack Deployment..."

# 1. Check/Install Docker
if ! command -v docker &> /dev/null; then
    echo "📦 Docker not found. Installing..."
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm get-docker.sh
    echo "✅ Docker installed."
else
    echo "✅ Docker is already installed."
fi

# 2. Setup Directory
APP_DIR="glitchtip-deploy"
mkdir -p $APP_DIR
cd $APP_DIR
echo "📂 Created directory: $APP_DIR"

# 3. Create docker-compose.yml
echo "📄 Writing configuration..."
cat << 'INNER_EOF' > docker-compose.yml

# -------------------------------------------------------------------------
# 🚀 Created and distributed by The AltStack
# 🌍 https://thealtstack.com
# -------------------------------------------------------------------------

version: '3.8'

services:
  glitchtip:
    image: glitchtip/glitchtip:latest
    container_name: glitchtip
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://glitchtip:glitchtip@db:5432/glitchtip
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=change_me_to_something_random
      - PORT=8000

  db:
    image: postgres:14
    container_name: glitchtip-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=glitchtip
      - POSTGRES_PASSWORD=glitchtip
      - POSTGRES_DB=glitchtip
    volumes:
      - glitchtip_db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: glitchtip-redis
    restart: unless-stopped

volumes:
  glitchtip_db_data:

INNER_EOF

# 4. Start Services
echo "🚀 Starting services..."
docker compose up -d

echo ""
echo "✅ Deployment Complete!"
echo "👉 Your glitchtip stack is running."
