#!/bin/bash
# 🚀 Auto-generated by The AltStack
# https://thealtstack.com

echo "🔵 Starting AltStack Deployment..."

# 1. Check/Install Docker
if ! command -v docker &> /dev/null; then
    echo "📦 Docker not found. Installing..."
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm get-docker.sh
    echo "✅ Docker installed."
else
    echo "✅ Docker is already installed."
fi

# 2. Setup Directory
APP_DIR="akaunting-deploy"
mkdir -p $APP_DIR
cd $APP_DIR
echo "📂 Created directory: $APP_DIR"

# 3. Create docker-compose.yml
echo "📄 Writing configuration..."
cat << 'INNER_EOF' > docker-compose.yml

# -------------------------------------------------------------------------
# 🚀 Created and distributed by The AltStack
# 🌍 https://thealtstack.com
# -------------------------------------------------------------------------

version: '3.8'

services:
  akaunting:
    image: akaunting/akaunting:latest
    container_name: akaunting
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_DATABASE=akaunting
      - DB_USERNAME=akaunting
      - DB_PASSWORD=akaunting

  db:
    image: mariadb:10.6
    container_name: akaunting-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=akaunting
      - MYSQL_USER=akaunting
      - MYSQL_PASSWORD=akaunting
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - akaunting_db_data:/var/lib/mysql

volumes:
  akaunting_db_data:

INNER_EOF

# 4. Start Services
echo "🚀 Starting services..."
docker compose up -d

echo ""
echo "✅ Deployment Complete!"
echo "👉 Your akaunting stack is running."
