
# -------------------------------------------------------------------------
# 🚀 Created and distributed by The AltStack
# 🌍 https://thealtstack.com
# -------------------------------------------------------------------------


services:
  postal:
    image: postalserver/postal:latest
    container_name: postal
    restart: unless-stopped
    ports:
      - "5000:5000"

