
# -------------------------------------------------------------------------
# 🚀 Created and distributed by The AltStack
# 🌍 https://thealtstack.com
# -------------------------------------------------------------------------


services:
  ollama-mistral:
    image: ollama/ollama:latest
    container_name: ollama-mistral
    restart: unless-stopped
    ports:
      - "11436:11434"
    volumes:
      - ollama_mistral:/root/.ollama

volumes:
  ollama_mistral:
