#!/bin/bash
# 🚀 Auto-generated by The AltStack
# https://thealtstack.com

echo "🔵 Starting AltStack Deployment..."

# 1. Check/Install Docker
if ! command -v docker &> /dev/null; then
    echo "📦 Docker not found. Installing..."
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm get-docker.sh
    echo "✅ Docker installed."
else
    echo "✅ Docker is already installed."
fi

# 2. Setup Directory
APP_DIR="zammad-deploy"
mkdir -p $APP_DIR
cd $APP_DIR
echo "📂 Created directory: $APP_DIR"

# 3. Create docker-compose.yml
echo "📄 Writing configuration..."
cat << 'INNER_EOF' > docker-compose.yml

# -------------------------------------------------------------------------
# 🚀 Created and distributed by The AltStack
# 🌍 https://thealtstack.com
# -------------------------------------------------------------------------

version: '3.8'

services:
  zammad:
    image: zammad/zammad-docker-compose:zammad-6.3.1-23
    container_name: zammad
    restart: unless-stopped
    depends_on:
      - zammad-postgresql
      - zammad-elasticsearch
      - zammad-redis
    ports:
      - "8080:8080"

  zammad-elasticsearch:
    image: bitnami/elasticsearch:8.12.2
    container_name: zammad-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node

  zammad-postgresql:
    image: postgres:15-alpine
    container_name: zammad-postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=zammad
      - POSTGRES_PASSWORD=zammad

  zammad-redis:
    image: redis:7.2-alpine
    container_name: zammad-redis
    restart: unless-stopped


INNER_EOF

# 4. Start Services
echo "🚀 Starting services..."
docker compose up -d

echo ""
echo "✅ Deployment Complete!"
echo "👉 Your zammad stack is running."
