#!/bin/bash
# 🚀 Auto-generated by The AltStack
# https://thealtstack.com

echo "🔵 Starting AltStack Deployment..."

# 1. Check/Install Docker
if ! command -v docker &> /dev/null; then
    echo "📦 Docker not found. Installing..."
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm get-docker.sh
    echo "✅ Docker installed."
else
    echo "✅ Docker is already installed."
fi

# 2. Setup Directory
APP_DIR="ceph-deploy"
mkdir -p $APP_DIR
cd $APP_DIR
echo "📂 Created directory: $APP_DIR"

# 3. Create docker-compose.yml
echo "📄 Writing configuration..."
cat << 'INNER_EOF' > docker-compose.yml

# -------------------------------------------------------------------------
# 🚀 Created and distributed by The AltStack
# 🌍 https://thealtstack.com
# -------------------------------------------------------------------------

services:
  ceph:
    image: quay.io/ceph/demo:latest
    container_name: ceph-demo
    privileged: true
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "8080:8080"
      - "6789:6789"
    environment:
      - MON_IP=127.0.0.1
      - CEPH_PUBLIC_NETWORK=0.0.0.0/0
      - CEPH_DEMO_UID=demo
      - CEPH_DEMO_ACCESS_KEY=demo
      - CEPH_DEMO_SECRET_KEY=demo
      - CEPH_DEMO_BUCKET=demobucket
      - DEMO_DAEMONS=all
    volumes:
      - ceph_data:/var/lib/ceph
      - ceph_config:/etc/ceph

volumes:
  ceph_data:
  ceph_config:

INNER_EOF

# 4. Start Services
echo "🚀 Starting services..."
docker compose up -d

echo ""
echo "✅ Deployment Complete!"
echo "👉 Your Ceph demo stack is running."
echo "   Dashboard:  http://localhost:5000"
echo "   S3 Gateway: http://localhost:8080"
