
# -------------------------------------------------------------------------
# 🚀 Created and distributed by The AltStack
# 🌍 https://thealtstack.com
# -------------------------------------------------------------------------


services:
  signoz-frontend:
    image: signoz/frontend:latest
    container_name: signoz-frontend
    restart: unless-stopped
    ports:
      - "3301:3301"

