
# -------------------------------------------------------------------------
# 🚀 Created and distributed by The AltStack
# 🌍 https://thealtstack.com
# -------------------------------------------------------------------------


services:
  erpnext:
    image: frappe/erpnext-worker:latest
    container_name: erpnext
    restart: unless-stopped
    ports:
      - "8000:8000"

