#!/bin/bash
# 🚀 Auto-generated by The AltStack
# https://thealtstack.com

echo "🔵 Starting AltStack Deployment..."

# 1. Check/Install Docker
if ! command -v docker &> /dev/null; then
    echo "📦 Docker not found. Installing..."
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm get-docker.sh
    echo "✅ Docker installed."
else
    echo "✅ Docker is already installed."
fi

# 2. Setup Directory
APP_DIR="mixpost-deploy"
mkdir -p $APP_DIR
cd $APP_DIR
echo "📂 Created directory: $APP_DIR"

# 3. Create docker-compose.yml
echo "📄 Writing configuration..."
cat << 'INNER_EOF' > docker-compose.yml

# -------------------------------------------------------------------------
# 🚀 Created and distributed by The AltStack
# 🌍 https://thealtstack.com
# -------------------------------------------------------------------------

version: '3.8'

services:
  mixpost:
    image: inovector/mixpost:latest
    container_name: mixpost
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "80:80"
    environment:
      - APP_URL=http://localhost
      - DB_HOST=db
      - DB_DATABASE=mixpost
      - DB_USERNAME=mixpost
      - DB_PASSWORD=mixpost
      - REDIS_HOST=redis

  db:
    image: mysql:8.0
    container_name: mixpost-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=mixpost
      - MYSQL_USER=mixpost
      - MYSQL_PASSWORD=mixpost
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mixpost_db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: mixpost-redis
    restart: unless-stopped

volumes:
  mixpost_db_data:

INNER_EOF

# 4. Start Services
echo "🚀 Starting services..."
docker compose up -d

echo ""
echo "✅ Deployment Complete!"
echo "👉 Your mixpost stack is running."
