# -------------------------------------------------------------------------
# 🚀 Created and distributed by The AltStack
# 🌍 https://thealtstack.com
# -------------------------------------------------------------------------


services:
  pocketbase:
    image: pocketbase/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command: serve --http=0.0.0.0:8090
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb/pb_data

volumes:
  pb_data:
