#!/bin/bash
# 🚀 Auto-generated by The AltStack
# https://thealtstack.com

echo "🔵 Starting AltStack Deployment..."

# 1. Check/Install Docker
if ! command -v docker &> /dev/null; then
    echo "📦 Docker not found. Installing..."
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm get-docker.sh
    echo "✅ Docker installed."
else
    echo "✅ Docker is already installed."
fi

# 2. Setup Directory
APP_DIR="plane-deploy"
mkdir -p $APP_DIR
cd $APP_DIR
echo "📂 Created directory: $APP_DIR"

# 3. Create docker-compose.yml
echo "📄 Writing configuration..."
cat << 'INNER_EOF' > docker-compose.yml

# -------------------------------------------------------------------------
# 🚀 Created and distributed by The AltStack
# 🌍 https://thealtstack.com
# -------------------------------------------------------------------------

version: '3.8'

services:
  plane-web:
    image: makeplane/plane-frontend:latest
    container_name: plane-frontend
    restart: unless-stopped
    depends_on:
      - plane-backend
    ports:
      - "3000:80"

  plane-backend:
    image: makeplane/plane-backend:latest
    container_name: plane-backend
    restart: unless-stopped
    depends_on:
      - plane-db
      - plane-redis
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://plane:plane@plane-db:5432/plane
      - REDIS_URL=redis://plane-redis:6379/
      - SECRET_KEY=replace-me-with-a-secure-key

  plane-db:
    image: postgres:15-alpine
    container_name: plane-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=plane
      - POSTGRES_PASSWORD=plane
      - POSTGRES_DB=plane
    volumes:
      - plane_db_data:/var/lib/postgresql/data

  plane-redis:
    image: redis:7-alpine
    container_name: plane-redis
    restart: unless-stopped
    volumes:
      - plane_redis_data:/data

volumes:
  plane_db_data:
  plane_redis_data:

INNER_EOF

# 4. Start Services
echo "🚀 Starting services..."
docker compose up -d

echo ""
echo "✅ Deployment Complete!"
echo "👉 Your plane stack is running."
